api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "price-manipulation"
type = "function"
uid = "c95c95be-2a05-9454-ecbe-dc29e56fef4d35a4f756"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
