api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "bundle-transfomation"
type = "function"
uid = "5fdf2ddd-c394-4032-0a77-cb3b3e0df149d8194a78"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
