api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "upsell-bundle-transformer"
type = "function"
uid = "f08feacc-a064-d428-ab5e-0f7eeae82109550d5ccf"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
